language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: 1.36.0

script:
  - cd "${TRAVIS_BUILD_DIR}/enumset"
  - cargo test
  - cargo test --features serde
  - cargo test --features alloc
  - cargo test --features std
  - cargo test --release --all-features
