language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: 1.36.0

script:
  - cd "${TRAVIS_BUILD_DIR}/enumset"
  - cargo test
  - cargo test --features serde
  - cargo test --release
  - cargo test --features serde --release
