name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        rustver: ["stable", "beta", "nightly", "1.56.0"]
        args: ["", "--features serde", "--features alloc", "--features std", "--release --all-features"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rustver }}
        default: true
    - uses: actions-rs/cargo@v1
      with:
        command: version
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: ${{ matrix.args }}
  build_no_std:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        target: thumbv6m-none-eabi
        default: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --target thumbv6m-none-eabi -p enumset_test_no_std
